---
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-store
  labels:
    app.kubernetes.io/name: file-store 
    app.kubernetes.io/version: 1.0.0
data:
  config.yaml: |
    server:
      host: localhost
      port: 8080
      debug: false
      tls: false
      log: debug

    cors:
      allowOrigins:
        - https://localhost:4000
      allowMethods:
        - DELETE
        - GET
        - POST
        - PUT
        - PATCH
        - HEAD
        - OPTIONS
      maxAge: 86400

    database:
      diskless: false
      encryption: false
      cacheSize: 0
      path: temp/database
