apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-store
  labels:
    app.kubernetes.io/name: file-store
    app.kubernetes.io/version: 1.0.0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi